# Permalinks
permalink:           pretty

# Setup
title:               Max Staley
tagline:             Essays on Data Science
url:                 http://huge-reality.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Max Staley
  url:               maxstaley.com
  email:             maxstaley@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/huge-reality

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
